[package]
name = "actix-web-codegen"
version = "0.2.2"
description = "Actix web proc macros"
readme = "README.md"
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web"
documentation = "https://docs.rs/actix-web-codegen"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"
workspace = ".."

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1", features = ["full", "parsing"] }
proc-macro2 = "1"

[dev-dependencies]
actix-rt = "1.0.0"
actix-web = "3.0.0-alpha.3"
futures-util = { version = "0.3.5", default-features = false }
